### ISSUE TITLE
Doesn't Work With Parsec

### ISSUE THREAD

**Issue by Antiiilluminati** [kleirof/Coop_View#1]
After my friend connects to my PC, the cultist keeps saying "Second monitor not detected"

This happens whether or not ETG or Parsec was open first

Keyboard input is still detected, but the mouse is slightly off? It accelerates at a different speed than my normal mouse.

**Comment by kleirof** [comment]
If only parsec no second physical monitor, you may create a virtual display use vdd software such as parsec-vdd, or Unity won't create a second window.
What do you mean slightly off? As described in the mod homepage, it's normal for the cursors to not coincide with the system one because I had to override it to achieve two mice. If you feel the acceleration uncomfortable you may increase or decrease it in control options.

**Comment by kleirof** [comment]
A patched version has been released. You can see if it solves the aiming problem.
